apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - common/ingress.yaml
  - common/cilium-bgp-peer-config.yaml
  - common/cilium-bgp-cluster-config.yaml
  - common/cilium-bgp-advertisement.yaml
  - dev/bgp-ip-pool.yaml
  - infra/bgp-ip-pool.yaml
  - prd/bgp-ip-pool.yaml
  - uat/bgp-ip-pool.yaml
