apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - docuseal-deployment.yaml
  - docuseal-service.yaml
  - docuseal-ingress.yaml
  - docuseal-pv.yaml
  - docuseal-pvc.yaml