apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-values
  namespace: flux-system
data:
  values.yaml: |
    authentik:
        secret_key: "cWBd29KB0rG7LrwqD01vd9ondt8x6UxxWqIe0H2b9segLG2n98zWwF9409n0cXjAoiyT+upQIcRVUCIn"
        error_reporting:
            enabled: false
        postgresql:
            password: "cWBd29KB0rG7LrwqD01vd9ondt8x6UxxWqIe0H2b9segLG2n98zWwF9409n0cXjAoiyT+upQIcRVUCIn"
    
    server:
        ingress:
            ingressClassName: traefik
            enabled: true
            hosts:
                - authentik.jonasg.be
    
    postgresql:
        enabled: true
        auth:
            password: "cWBd29KB0rG7LrwqD01vd9ondt8x6UxxWqIe0H2b9segLG2n98zWwF9409n0cXjAoiyT+upQIcRVUCIn"
    redis:
        enabled: true
