apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: "36.3.0"
    helm:
      releaseName: traefik
      values: |
        api:
          dashboard: true
          insecure: false
        metrics:
          prometheus:
            enabled: true
        ingressRoute:
          dashboard:
            enabled: true
        service:
          labels:
            env: infra
            service.kubernetes.io/cilium-advertised-bgp: "true"
          spec:
            type: LoadBalancer
            loadBalancerIP: 10.0.1.3
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
