apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyseerr-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.3.100
    path: "/mnt/user/kubernetes/jellyseerr"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-pvc
  namespace: jellyseerr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi