kubernetes_version: "1.34.3"

pod_network_cidr: "172.16.0.0/16"
service_network_cidr: "172.17.0.0/16"

# kube-vip
kubevip_version: "v0.8.2"
kubevip_interface: "eth0"
kubevip_address: "10.0.1.2"

# Cilium
cilium_version: "v1.18.4"
