apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service-clusterip.yaml
  - service-lb.yaml
  - configmap.yaml
  - pv-adguard-config.yaml
  - pv-adguard-work.yaml
  - pvc-adguard-config.yaml
  - pvc-adguard-work.yaml