apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "ip-pool-bgp-prd"
spec:
  allowFirstLastIPs: "No"
  blocks:
    - start: "10.0.2.3"
      stop: "10.0.2.10"
  serviceSelector:
    matchLabels:
      service.kubernetes.io/cilium-advertised-bgp: "true"
      env: "prd"
