apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "ip-ppool-bgp-prd"
spec:
  allowFirstLastIPs: "No"
  blocks:
    - cidr: "10.0.2.0/24"
  serviceSelector:
    matchLabels:
      service.kubernetes.io/cilium-adverstised-bgp: "true"
      env: "prd"
