resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- pvc.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/instance: open-webui

images:
- name: ghcr.io/open-webui/open-webui
  newName: ghcr.io/open-webui/open-webui
  newTag: main
