apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-nfs-pvc
  namespace: open-webui
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: open-webui
