apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: mcp
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiam9uYXNnb3ZhZXJ0cyIsInBhc3N3b3JkIjoiZ2hwX2FXcVRZaGdEeFl1alhMcTNDT05rNDFlMWRuNmNNVjFsQTVpNSIsImF1dGgiOiJhbTl1WVhObmIzWmhaWEowY3pwbmFIQmZZVmR4VkZsb1owUjRXWFZxV0V4eE0wTlBUbXMwTVdVeFpHNDJZMDFXTVd4Qk5XazEifX19
