apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cadvisor
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/google/cadvisor.git
    targetRevision: master
    path: deploy/kubernetes/base
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: cadvisor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
