---
- name: Debug Kubernetes version
  hosts: masters,workers
  gather_facts: false
  vars:
    kubernetes_version: "1.30.3"
  tasks:
    - name: Debug variable
      ansible.builtin.debug:
        msg: "curl -fsSL https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version | regex_replace('^(\\d+\\.\\d+)\\..*$', '\\1') }}/deb/Release.key"
