---
- name: Debug Kubernetes version
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Debug variable
      ansible.builtin.debug:
       msg: kubeadm init \
        --kubernetes-version={{ kubernetes_version }} \
        --pod-network-cidr={{ pod_network_cidr }} \
        --service-cidr={{ service_network_cidr }} \
        --apiserver-advertise-address={{ kubevip_address }}
