apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trouw-rsvp
  namespace: trouw-rsvp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi