apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "ip-pool-bgp-infra"
spec:
  blocks:
    - start: "10.0.1.3"
      stop: "10.0.1.10"
  serviceSelector:
    matchLabels:
      service.kubernetes.io/cilium-advertised-bgp: "true"
      env: "infra"
