apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment-n8n.yaml
  - deployment-postgres.yaml
  - svc.yaml
  - svc-postgres.yaml
  - ingress.yaml
  - pv-n8n.yaml
  - pv-postgres.yaml
  - pvc-n8n.yaml
  - pvc-postgres.yaml
  - secret.yaml