# ./kubernetes/n8n/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
  namespace: n8n
type: Opaque
data:
  POSTGRES_USER: bjhu
  POSTGRES_PASSWORD: bjhu
  POSTGRES_DB: bjhu
  DB_POSTGRESDB_USER: bjhu
  DB_POSTGRESDB_PASSWORD: bjhu
  N8N_BASIC_AUTH_USER: YWRtaW4=
  N8N_BASIC_AUTH_PASSWORD: YWRtaW4=