apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret.yaml
  - pvc-db.yaml
  - deployment-db.yaml
  - service-db.yaml
  - deployment-app.yaml
  - service-app.yaml
  - ingress.yaml