apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: umami-db-pvc
  namespace: umami
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi