apiVersion: v1
kind: Secret
metadata:
  name: umami-secrets
  namespace: umami
type: Opaque
stringData:
  POSTGRES_DB: "umami"
  POSTGRES_USER: "umami"
  POSTGRES_PASSWORD: "umami"
  DATABASE_URL: "postgresql://umami:umami@umami-db:5432/umami"
  APP_SECRET: "replace-me-with-a-random-string"