apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qr-generator
  namespace: qr-generator
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi